# Generated by Django 4.2.2 on 2023-06-27 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='tg_id',
            field=models.IntegerField(db_index=True, verbose_name='id in telegram'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='username',
            field=models.CharField(db_index=True, max_length=255, verbose_name='username in telegram'),
        ),
        migrations.CreateModel(
            name='ListGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=255, verbose_name='game name')),
                ('players', models.JSONField(verbose_name='players')),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_games', to='api_data.tguser', verbose_name='administrator')),
            ],
        ),
    ]
