# Generated by Django 4.2.2 on 2023-06-27 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_data', '0002_alter_tguser_tg_id_alter_tguser_username_listgames'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='listgames',
            table='TG_list_games',
        ),
    ]
