# Generated by Django 4.2.2 on 2023-06-27 12:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_data', '0003_alter_listgames_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listgames',
            name='players',
        ),
        migrations.AddField(
            model_name='listgames',
            name='identify_game',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(0)], verbose_name='id game'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listgames',
            name='game_name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='game name'),
        ),
        migrations.CreateModel(
            name='GameCSP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_players', models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)], verbose_name='number of players')),
                ('in_game', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)], verbose_name='players in game')),
                ('players', models.JSONField(verbose_name='players')),
                ('list_games', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='api_data.listgames', verbose_name='connection to list')),
            ],
        ),
    ]
