# Generated by Django 4.2.2 on 2023-06-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_data', '0005_alter_listgames_identify_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='tg_id',
            field=models.IntegerField(db_index=True, unique=True, verbose_name='id in telegram'),
        ),
    ]
