# Generated by Django 4.2.2 on 2023-06-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_data", "0007_alter_listgames_identify_game"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listgames",
            name="game_name",
            field=models.CharField(
                db_index=True, max_length=255, unique=True, verbose_name="game name"
            ),
        ),
    ]
