# Generated by Django 4.2.2 on 2023-06-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_data", "0008_alter_listgames_game_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tguser",
            name="username",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                verbose_name="username in telegram",
            ),
        ),
    ]
