version: "3.9"

services:
  dj_app:
    build:
      context: ./tg_bot_data
      dockerfile: Dockerfile
    container_name: tg_bot_dj
    command: bash -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py create_superuser &&
      python manage.py collectstatic --noinput &&
      gunicorn tg_bot_data.wsgi:application --bind 0.0.0.0:8000
      "
    volumes:
      - ./tg_bot_data:/am
    env_file:
      - ./tg_bot_data/.env
    depends_on:
      - db

  tg_bot:
    build:
      context: ./Version_1
      dockerfile: Dockerfile
    container_name: tg_bot
    command: bash -c "
      python main.py
      "
    volumes:
      - ./Version_1:/am
    env_file:
      - ./Version_1/.env
    depends_on:
      - dj_app
    links:
      - dj_app
      - nginx

  db:
    image: postgres:15-alpine
    container_name: tg_bot_base
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    env_file:
      - ./tg_bot_data/.env

  nginx:
    build: nginx
    container_name: tg_bot_nginx
    ports:
      - "80:80"
    depends_on:
      - dj_app
    volumes:
      - static:/am/static
      - media:/am/media

volumes:
  postgres_data:
  static:
  media: