version: "3.9"

services:
  app:
    build:
      dockerfile: ./dockerfile
    container_name: nko
    command: bash -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py create_superuser &&
      python manage.py collectstatic --noinput &&
      gunicorn NKO.wsgi:application --bind 0.0.0.0:8000
      "
    volumes:
      - .:/am
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    container_name: nko_postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    env_file:
      - .env

  nginx:
    build: nginx
    container_name: nko_nginx
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - static:/am/static
      - media:/am/media

  redis:
    image: redis:alpine
    hostname: redis

  celery_worker:
    build:
      dockerfile: ./dockerfile
    container_name: nko-celery_worker_1
    hostname: worker_1
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    env_file:
      - .env
    volumes:
      - .:/am
    command: celery -A NKO worker -l info
    links:
      - redis
    depends_on:
      - redis
      - db

  flower:
    build:
      dockerfile: ./dockerfile
    hostname: nko-flower
    command: celery -A NKO flower
    volumes:
      - .:/am
    links:
      - redis
    depends_on:
      - redis
    ports:
      - "5555:5555"




volumes:
  postgres_data:
  static:
  media: