version: "3.9"

services:
  dj_app:
    build:
#      context: ./tg_bot_data
      dockerfile: Dockerfile
    container_name: test_tg_bot_dj
    command: bash -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py create_superuser &&
      python manage.py collectstatic --noinput &&
      gunicorn tg_bot_data.wsgi:application --bind 0.0.0.0:8000
      "
    volumes:
      - .:/am
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    container_name: test_tg_bot_base
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    env_file:
      - .env

  nginx:
    build: nginx
    container_name: test_tg_bot_nginx
    ports:
      - "80:80"
    depends_on:
      - dj_app
    volumes:
      - static:/am/static
      - media:/am/media

volumes:
  postgres_data:
  static:
  media: